### PR TITLE
use popstate to close and reopen colorbox when using back/forward browse...

### PR DESCRIPTION
**Pull request by justinsteele**
...r buttons, fixes colszowka/simplecov#263

### CODE REVIEW

**Comment by whatasunnyday** [comment]
Just a quick heads up, _AllFiles is not the only place where you might want to go back to. Every group is appended with a _. In hindsight, I probably should have used window.onpopstate instead of the jquery library because the jquery library is a polyfill for old browsers and very few developers will probably running that version. Good PR anyways :+1:. As long as one of ours get merged, I'll be happy.

**Comment by justinsteele** [comment]
Thanks @whatasunnyday ! I made the change you suggested, and while doing so found a bug that I fixed. Bonus! :)

**Comment by bf4** [comment]
Which should I merge?

**Comment by whatasunnyday** [comment]
@bf4 I don't care if its @justinsteele or mine. Since you're the maintainer, whichever is easier to maintain ;).

**Comment by justinsteele** [comment]
In my completely biased view.. haha.. If no one sees any problems with this one, I'd use it as it fixes the forward button as well.

**Comment by bf4** [comment]
Well, my POV is not having tested it, relying on both of you having verified each other's, and punting on picking between the two... :)

**Comment by colszowka** [comment]
Shipped as part of simplecov-html 0.9.0. SimpleCov 0.9.2 with a loosened version constraint will ship in a couple minutes. Thanks @whatasunnyday and @justinsteele!

**Pull request merged**
