### PR TITLE
Autofocus search input

### PR DESCRIPTION
**Pull request by hedgesky**
Added one line to `application.js` to autofocus filtering input so user can start typing instantly.

### CODE REVIEW

**Comment by hedgesky** [comment]
Travis build failes on Ruby 1.8.7 because CI server tries to use new version of `rake` which supports only Ruby 1.9.3 and higher. Should I set proper version of `rake` in Gemfile?

**Comment by sferik** [comment]
@hedgesky I’ve fixed this is `master`. Can you please rebase and force push your branch?

**Comment by hedgesky** [comment]
Done.

**Comment by hedgesky** [comment]
Hello!
Are there any things to do before merging this to master?

**Comment by hedgesky** [comment]
Hi!
Let me remind you about this PR once again 🙂

**Comment by PragTob** [comment]
:wave: 

Thanks for the ping, seens semi taking over some maintenance duties I ahven't really gotten to the formatter yet. Appologies and merge :)

**Pull request merged**
