### PR TITLE
Remove RubyGems dep

### LINKED ISSUE #38: Can't be used without rubygems loaded
While rubygems is loaded by default on 1.9+, there are situations where it is desirable not to load it, and you can use ruby's `--disable=gem` flag to disable it.  We're trying to update RSpec's travis builds to run with rubygems disable, and are running into unitinialized constant by your use of `Gem::Version`:

https://github.com/colszowka/simplecov-html/blob/65238a35cda44956e87dd520086095cbf1f2370d/lib/simplecov-html.rb#L8

Can this version constraint be moved into the gemspec?  That would allow bundler to ensure this and simplecov are compatible, where as it can't due that when it's purely a runtime check like you have now.

### PR DESCRIPTION
**Pull request by bf4**
Fixes #38

### CODE REVIEW

**Comment by sferik** [comment]
:+1:

It would be nice if `simplecov` exposed the internal structure of its version number, so you didn’t have to parse a string. For example, see the [`Twitter::Version` class in the `twitter` gem](https://github.com/sferik/twitter/blob/master/lib/twitter/version.rb).

**Comment by bf4** [comment]
@sferik Yeah, but then I have to go back and first fix and release `simplecov`.. lulz

**Comment by bf4** [comment]
@sferik wanna merge or add to it?

**Comment by myronmarston** [comment]
> It would be nice if simplecov exposed the internal structure of its version number, so you didn’t have to parse a string. For example, see the Twitter::Version module in the twitter gem.

For VCR, I did a similar thing, but took a different approach:

https://github.com/vcr/vcr/blob/v2.9.3/lib/vcr/version.rb

It's still a string, but the string has some singleton methods to get the different parts.  I have no idea if anyone has ever used those methods, though.

**Comment by sferik** [comment]
@myronmarston Nice. I just committed some similar [changes to `SimpleCov::VERSION`](https://github.com/colszowka/simplecov/commit/d66de666343853eefe3de8a9fe45d65dea303521). Of course, this will only apply to future versions, so it won’t be helpful in this particular case.

**Pull request merged**
