### PR TITLE
Fix back button.

### PR DESCRIPTION
**Pull request by whatasunnyday**
This should fix https://github.com/colszowka/simplecov/issues/263

It's unclear to me on where and how to add tests for this. Any guidance is appreciated.

### CODE REVIEW

**Comment by justinsteele** [comment]
What are the chances we both decided to fix this today? Guess I should have checked that bug once I got back to my computer this evening..

https://github.com/colszowka/simplecov-html/pull/36

**Comment by whatasunnyday** [comment]
@justinsteele Sorry about that. :(

**Comment by bf4** [comment]
Closed by https://github.com/colszowka/simplecov-html/pull/36

**Comment by colszowka** [comment]
@whatasunnyday Thanks for your contribution. I will add both you and @justinsteele to the changelog for the 0.9.2 release of SimpleCov itself.

**Pull request closed without merging**
